pipeline:
  projectIdentifier: Drone_Plugins
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ebtcongithub
        repoName: drone-buildx-acr
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: linux-amd64-acr
        identifier: linuxamd64acr
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build binaries
                  identifier: BuildPush
                  spec:
                    connectorRef: Plugins_Docker_Hub_Connector
                    image: golang:1.23.0
                    shell: Sh
                    command: |-
                      # force go modules
                      export GOPATH=""

                      # disable cgo
                      export CGO_ENABLED=0

                      set -e
                      set -x

                      # linux
                      export GOOS=linux GOARCH=amd64

                      go build -v -ldflags "-X main.build=<+pipeline.sequenceId>" -a -tags netgo -o release/linux/amd64/buildx-acr ./cmd/drone-buildx-acr
                  when:
                    stageStatus: Success
                    condition: <+codebase.build.type> != "tag"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry
                  identifier: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: dock_con_ebt
                    repo: plugins/buildx-acr
                    tags:
                      - linux-amd64
                    caching: false
                    dockerfile: docker/acr/Dockerfile.linux.amd64
                  when:
                    stageStatus: Success
                    condition: |
                      <+codebase.build.type> == "branch" 
        variables:
          - name: DRONE_REPO_OWNER
            type: String
            description: ""
            required: false
            value: drone-plugins
  allowStageExecutions: true
  identifier: dronebuildxacrharness_ebttest
  name: drone-buildx-acr-harness - ebt-test
